### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by rupeshchandgude** [mzucker/page_dewarp#13]
Hello, I have ran the code as mention in comments using python page_dewarp.py Img.
Following error occurred after running the code.

> python page_dewarp.py IMG_20190717_114448.jpg 
loaded IMG_20190717_114448.jpg with size 2250x4000 and resized to 375x667
Traceback (most recent call last):
  File "page_dewarp.py", line 915, in <module>
    main()
  File "page_dewarp.py", line 867, in main
    cinfo_list = get_contours(name, small, pagemask, 'text')
  File "page_dewarp.py", line 450, in get_contours
    cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

**Comment by namdaoduy** [comment]
@rupeshchandgude Same issue, and I found the solution here
https://stackoverflow.com/questions/40278444/error-using-cv2-findcontours-with-python
Maybe the cause of opencv version
Just change the line 450:
`_, contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,
                                      cv2.CHAIN_APPROX_NONE)`
into
`contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL,
                                      cv2.CHAIN_APPROX_NONE)`
Worked for me

**Comment by rupeshchandgude** [comment]
Thanks @namdaoduy. Now it is working for me.
