### ISSUE TITLE
No module named cv2 / add requirements.txt file?

### ISSUE THREAD

**Issue by aurelg** [mzucker/page_dewarp#2]
Very nice project. However, I just can't make it work because of missing cv2 requirement (and possibly others):

```
Traceback (most recent call last):
  File "../page_dewarp.py", line 15, in <module>
    import cv2
ImportError: No module named cv2
```

Perhaps you could add a [requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html) file to your repo?

**Comment by mzucker** [comment]
Changed readme in 438bdc614e0d7cffd948cde50f910f775956dc73 and added a requirements file in 5c587b5bfa6718656bb4cf82260d2b98f4fe5682 as you suggested.
