### ISSUE TITLE
How to generate the "page_warping.gif" ?

### ISSUE THREAD

**Issue by huntzhan** [mzucker/page_dewarp#26]
Hi Matt,
I'm wondering if you could share the code snippet for generating the animation? 
![](https://mzucker.github.io/images/page_dewarp/page_warping.gif)
Thanks for your attention. I’m looking forward to your reply.

**Comment by rramphal** [comment]
It looks like Matt moved the visualization code out of the repo. I believe the code is here: https://github.com/mzucker/page_dewarp/commit/d3257d7b564bff994187a872d00537bc2fda7d3d.

**Comment by huntzhan** [comment]
@rramphal thank you!
