### ISSUE TITLE
Omission of `from PIL` for `import Image` means page_dewarp doesn't work under Pillow

### ISSUE THREAD

**Issue by benjolitz** [mzucker/page_dewarp#3]
At https://github.com/mzucker/page_dewarp/blob/master/page_dewarp.py#L16 you see `import Image`.

Pillow doesn't expose a top level Image class in sys.modules -- it is only available under the PIL module.

Changing the line to `from PIL import Image` from `import Image` should be backwards compatible with both PIL and Pillow.

**Comment by mzucker** [comment]
Fixed, thanks.
