### ISSUE TITLE
syntax error line 739

### ISSUE THREAD

**Issue by Alessio-R** [mzucker/page_dewarp#5]
I'm trying to run the script but it gives me an "invalid syntax" error at line 739 `print '  initial objective is', objective(params)`.

I'm using Python 3.5 (I installed WinPython with scipy, numpy and pillow) and OpenCV 3.2, which I installed following the instructions found here: https://pythonarena.wordpress.com/2016/03/07/scientific-python-on-windows/

**Comment by zacniewski** [comment]
This repo requires Python2.
